apiVersion: v1
kind: Service
metadata:
  name: tukano-service
spec:
  selector:
    app: tukano-app  # Matches the label in deployment.yaml
  ports:
  - protocol: TCP
    port: 80          # Port exposed to the host
    targetPort: 8080  # Port inside the container
  type: NodePort      # Exposes the service on a Node's IP and a specific port
